const express=require("express"),fs=require("fs"),path=require("path"),QRCode=require("qrcode"),pino=require("pino");
const {default:makeWASocket,useMultiFileAuthState,makeCacheableSignalKeyStore,fetchLatestBaileysVersion,Browsers,DisconnectReason,delay}=require("@whiskeysockets/baileys");
const app=express(),PORT=+process.env.PORT||10000,ROOT=path.join(__dirname,"sessions"),log=pino({level:"fatal"}),jobs=new Map();
fs.mkdirSync(ROOT,{recursive:true});app.use(express.json({limit:"32kb"}));
const d=v=>String(v||"").replace(/\D/g,""),ok=v=>/^\d{7,15}$/.test(v),dir=n=>path.join(ROOT,n),creds=n=>path.join(dir(n),"creds.json");
const html=`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Danish Khan WA Login</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#05060a;color:white;font-family:system-ui;text-align:center}main{width:min(650px,92%);margin:45px auto}.tag{display:inline-block;padding:8px 14px;border:1px solid #394052;border-radius:99px;color:#cbd3e2;font-size:11px;font-weight:900;letter-spacing:.15em}h1{font-size:clamp(38px,9vw,60px);line-height:1;margin:18px 0}.sub{color:#929daf}.card{margin-top:25px;padding:24px;border:1px solid #2b3342;border-radius:26px;background:#0b0e15}.tabs,.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tabs{margin-bottom:18px}button,input{width:100%;padding:16px;border-radius:14px;border:1px solid #354052;background:#151922;color:white;font-size:15px;font-weight:800}input{text-align:left;font-size:18px}.active,.primary{background:linear-gradient(135deg,#7047ff,#a16cff);border:0}.box{margin-top:18px;padding:18px;border:1px dashed #465165;border-radius:16px}.code{font-size:32px;letter-spacing:.16em;font-weight:900;margin:8px}.qr{width:min(270px,85%);background:white;padding:8px;border-radius:10px;margin:10px}.status{margin-top:15px;padding:13px;background:#070a10;border-radius:12px;color:#b5bfd0}.good{color:#00e3a0}.bad{color:#ff6d87}.note{font-size:12px;color:#718097;margin-top:15px;line-height:1.5}@media(max-width:500px){.grid{grid-template-columns:1fr}.card{padding:18px}}</style>
<main><span class=tag>DANISH KHAN • WA LOGIN</span><h1>WhatsApp Login</h1><div class=sub>QR + Pair Code</div><section class=card>
<div class=tabs><button id=qt class=active>QR Login</button><button id=pt>Pair Code</button></div>
<div id=qv><button id=qrgo class=primary>Generate QR</button><div id=qb class=box hidden><b>SCAN WITH WHATSAPP</b><img id=qr class=qr></div></div>
<div id=pv hidden><input id=num inputmode=numeric value=917050407246><br><br><button id=pc class=primary>Generate Pair Code</button><div id=pb class=box hidden><small>PAIR CODE</small><div id=code class=code></div></div></div>
<div class=grid><button id=check>Check Login</button><button id=reset>New Session</button></div><button id=down style="margin-top:10px">Download creds.json</button><div id=st class=status>Ready.</div><div class=note>QR is recommended if WhatsApp rejects pairing-code login. Use only your own account.</div>
</section></main><script>
let number="",timer;const $=x=>document.getElementById(x),say=(t,c="")=>{$("st").className="status "+c;$("st").textContent=t},poll=()=>{clearInterval(timer);timer=setInterval(async()=>{if(!number)return;try{let x=await(await fetch("/api/status?number="+encodeURIComponent(number))).json();if(x.status==="connected"){clearInterval(timer);say("LOGIN SUCCESS — WhatsApp linked.","good")}else if(x.status==="failed"||x.status==="logged_out"){clearInterval(timer);say(x.error||"Connection closed","bad")}}catch{}},2000)};
$("qt").onclick=()=>{$("qv").hidden=false;$("pv").hidden=true;$("qt").className="active";$("pt").className=""};$("pt").onclick=()=>{$("qv").hidden=true;$("pv").hidden=false;$("pt").className="active";$("qt").className=""};
$("qrgo").onclick=async()=>{say("Starting QR login…");try{let x=await(await fetch("/api/qr",{method:"POST"})).json();if(!x.ok)throw Error(x.error);number=x.number;$("qr").src=x.qr;$("qb").hidden=false;say("WhatsApp → Linked devices → Link a device → Scan QR.","good");poll()}catch(e){say(e.message,"bad")}};
$("pc").onclick=async()=>{number=$("num").value.replace(/\\D/g,"");if(!/^\\d{7,15}$/.test(number))return say("Invalid number","bad");say("Generating pair code…");try{let x=await(await fetch("/api/pair",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({number})})).json();if(!x.ok)throw Error(x.error);$("code").textContent=x.code;$("pb").hidden=false;say("Enter code in WhatsApp → Linked devices → Link with phone number.","good");poll()}catch(e){say(e.message,"bad")}};
$("check").onclick=async()=>{if(!number)return say("Start login first");let x=await(await fetch("/api/status?number="+encodeURIComponent(number))).json();say("Status: "+x.status+(x.credsSaved?" • creds.json saved":""))};
$("reset").onclick=async()=>{if(number)await fetch("/api/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({number})});clearInterval(timer);$("qb").hidden=true;$("pb").hidden=true;say("Fresh session ready.","good")};
$("down").onclick=()=>number&&(location.href="/api/download?number="+encodeURIComponent(number));
</script>`;
async function socket(number){
 let old=jobs.get(number);try{old?.sock?.end?.()}catch{}jobs.delete(number);
 let x=dir(number);if(fs.existsSync(x))fs.rmSync(x,{recursive:true,force:true});fs.mkdirSync(x,{recursive:true});
 let {state,saveCreds}=await useMultiFileAuthState(x),{version}=await fetchLatestBaileysVersion();
 let sock=makeWASocket({version,auth:{creds:state.creds,keys:makeCacheableSignalKeyStore(state.keys,log)},logger:log,browser:Browsers.ubuntu("Chrome"),markOnlineOnConnect:true,printQRInTerminal:false,syncFullHistory:false,connectTimeoutMs:60000,keepAliveIntervalMs:10000});
 let j={sock,status:"connecting",error:null,qr:null};jobs.set(number,j);sock.ev.on("creds.update",saveCreds);
 sock.ev.on("connection.update",async u=>{if(u.qr)try{j.qr=await QRCode.toDataURL(u.qr)}catch{}if(u.connection==="open"){j.status="connected";j.error=null}if(u.connection==="close"){let c=u.lastDisconnect?.error?.output?.statusCode;j.status=c===DisconnectReason.loggedOut?"logged_out":"failed";j.error=c?`WhatsApp connection closed (${c})`:"WhatsApp connection closed"}});
 return {sock,j};
}
app.get("/",(q,r)=>r.type("html").send(html));app.get("/health",(q,r)=>r.json({ok:true}));
app.post("/api/qr",async(q,r)=>{let n="qr-"+Date.now();try{let {j}=await socket(n);for(let i=0;i<40&&!j.qr;i++)await delay(250);if(!j.qr)throw Error("QR not received; check Render logs");r.json({ok:true,number:n,qr:j.qr})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.post("/api/pair",async(q,r)=>{let n=d(q.body?.number);if(!ok(n))return r.status(400).json({ok:false,error:"Invalid number"});try{let {sock}=await socket(n),code=await sock.requestPairingCode(n);r.json({ok:true,code})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.get("/api/status",(q,r)=>{let n=d(q.query.number),j=jobs.get(n),saved=ok(n)&&fs.existsSync(creds(n));r.json({ok:true,status:saved?"connected":j?.status||"idle",error:j?.error||null,credsSaved:saved})});
app.get("/api/download",(q,r)=>{let n=d(q.query.number),f=creds(n);if(!ok(n)||!fs.existsSync(f))return r.status(404).send("creds.json not ready");r.download(f,"creds.json")});
app.post("/api/reset",(q,r)=>{let n=d(q.body?.number);try{jobs.get(n)?.sock?.end?.()}catch{}jobs.delete(n);if(ok(n)&&fs.existsSync(dir(n)))fs.rmSync(dir(n),{recursive:true,force:true});r.json({ok:true})});
app.listen(PORT,"0.0.0.0",()=>console.log("Danish Khan WA Login on "+PORT));
